### ISSUE TITLE
Test class not found via keyboard shortcut in AndroidStudio

### ISSUE THREAD

**Issue by mpost** [kageiit/gradle-robojava-plugin#11]
Hitting <code>ctrl+shift+t</code> does not find the corresponding test class in AndroidStudio. Same goes for the other direction when using the shortcut to navigate to the implementation class.

**Comment by kageiit** [comment]
This is a limitation of the ide  that I could not find a way around. This is because the main project only knows about main sources and the stub project only knows about test sources and they are different kinds of projects.

I would just Ctrl+shift+O for the class you are looking for or click attach sources at the top right when this happens and just point to the relevant source directory in your project.

If you find a way to do this via the plugin itself, you are welcome to contribute :)
